name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Package the application
      run: dotnet publish --configuration Release -o publish/gossipIt
    - name: Publish artifact
      uses: actions/upload-artifact@master
      with:
        name: webapp
        path: publish/gossipIt
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: webapp
        path: ./webapp

    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: "mygossipitapp01"
        publish-profile: ${{ secrets.publishSettings }}
        package: webapp